FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install --silent
COPY . .
RUN npm run build

FROM node:12.2.0-alpine
RUN yarn global add serve
WORKDIR /app
COPY --from=build /app/build .
EXPOSE 80
CMD ["serve", "-p", "80", "-s", "."]
