export const API_SEARCH = "http://omdbapi.com/?apikey=94f18c22&s=";
export const API_MOVIE_DETAIL = "http://omdbapi.com/?apikey=94f18c22&i=";

export const SEARCH_MOVIE = "SEARCH_MOVIE";




// ACTION NAMES
export const SEARCH_INIT = "SEARCH_INIT";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const LOAD_FAVORITE_MOVIES = "LOAD_FAVORITE_MOVIES";
export const LOAD_FAVORITE_MOVIES_SUCCESS = "LOAD_FAVORITE_MOVIES_SUCCESS";

export const LOAD_MOVIE = "LOAD_MOVIE";
export const LOAD_MOVIE_SUCCESS = "LOAD_MOVIE_SUCCESS";
export const LOAD_MOVIE_ERROR = "LOAD_MOVIE_ERROR";
export const LOAD_MOVIE_FAVORITE = "LOAD_MOVIE_FAVORITE";

export const ADD_FAVORITE_MOVIE = "ADD_FAVORITE_MOVIE";
export const REMOVE_FAVORITE_MOVIE = "REMOVE_FAVORITE_MOVIE";

export const ADDED_FAVORITE_MOVIE = "ADDED_FAVORITE_MOVIE";
export const REMOVED_FAVORITE_MOVIE = "REMOVED_FAVORITE_MOVIE";
